[package]
name = "adapter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

description = "Platform-specific adapters for Rabbit"

[dependencies]
schema = { path = "../schema" }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
xelevate = { version = "0.1.2", registry = "crates-io" }
image = "0.25"
sha2 = "0.10"
fltk = { workspace = true }
rabbit-diag = { path = "../rabbit-diag" }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_Com", "Win32_NetworkManagement_IpHelper"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
ksni = { version = "0.3" }

[target.'cfg(not(target_os = "linux"))'.dependencies]
tray-icon = "0.23"
