[package]
name = "adapter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

description = "Platform-specific adapters for Rabbit"

[dependencies]
schema = { path = "../schema" }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
xelevate = { version = "0.1.2", registry = "crates-io" }
fltk = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_Com", "Win32_NetworkManagement_IpHelper"] }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
